### ISSUE TITLE
Implement removeOption(s) methods for QEmuCommandLine class.

### ISSUE THREAD

**Issue by dsfb** [shevek/qemu-java#2]
They could be:
void  removeOption(Class<T> type)
void  removeOptions(Class<T> type)
void 	removeOptions()
.

**Comment by shevek** [comment]
Options are actually a tree, not a list, and not all nodes in the option-tree have mutable children. So those API methods would be a little misleading.

I'd rather you construct a new QEmuCommandLine and copy the options you DO want than attempt to implement full mutation.

**Comment by shevek** [comment]
If the above answer does not satisfy, can you please give a more explicit example of what you're trying to do that needs remove?

For example, most of the *Recipe classes extend QEmuOptionsList, but are essentially immutable.

**Comment by dsfb** [comment]
Dear shevek.Thanks for your answers. I thought in your suggestion, too. I will follow her.
By the way, You can to close this issue.
Best Regards,Daniel Bruno. 


     Em Segunda-feira, 6 de Abril de 2015 17:13, Shevek <notifications@github.com> escreveu:
   

 If the above answer does not satisfy, can you please give a more explicit example of what you're trying to do that needs remove?For example, most of the *Recipe classes extend QEmuOptionsList, but are essentially immutable.—
